name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  validate-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Extract tag version
      id: tag_version
      run: |
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
        echo "Tag version: $TAG_VERSION"

    - name: Extract pyproject.toml version
      id: pyproject_version
      run: |
        PYPROJECT_VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
        echo "version=$PYPROJECT_VERSION" >> $GITHUB_OUTPUT
        echo "pyproject.toml version: $PYPROJECT_VERSION"

    - name: Validate version match
      run: |
        if [ "${{ steps.tag_version.outputs.version }}" != "${{ steps.pyproject_version.outputs.version }}" ]; then
          echo "❌ Error: Git tag version (${{ steps.tag_version.outputs.version }}) does not match pyproject.toml version (${{ steps.pyproject_version.outputs.version }})"
          exit 1
        fi
        echo "✅ Version validation passed: ${{ steps.tag_version.outputs.version }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install -e ".[dev]"

    - name: Run tests
      run: |
        pytest

    - name: Build package
      run: |
        python -m build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
